services:
  mysqldb:
    container_name: TheRaven_MySQL
    image: mysql
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: the_raven
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: bestuser
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PUBLIC_KEY: insecure_public_key