spring:
  datasource:
    url: jdbc:mysql://localhost:3309/the_raven?useSSL=false&&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: bestuser
    password: bestuser
spring.jpa:
  hibernate.ddl-auto: update
